# Generated by Django 4.2.3 on 2023-07-07 00:28

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin1'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergia',
            field=models.CharField(default=builtins.dir, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='correo',
            field=models.CharField(default=builtins.dir, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin1',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin1',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
    ]
