# Generated by Django 4.2.4 on 2023-08-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paciente_alergia_paciente_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='paciente_fotos/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
