# Generated by Django 4.2.4 on 2023-08-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_paciente_altura_paciente_foto_paciente_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(null=True, upload_to='paciente_fotos'),
        ),
    ]
